const fs = require('fs')
const path = require('path')
const root = path.join(__dirname, '..', 'dist')
const j = JSON.parse(fs.readFileSync(path.join(root, 'plugin.json'), 'utf8'))
console.log('main=', j.main)
console.log('hasDev=', !!j.development)
console.log('cmds=', JSON.stringify(j.features[0].cmds))
const h = fs.readFileSync(path.join(root, 'index.html'), 'utf8')
console.log('hasApp=', h.includes('id="app"'))
console.log('hasCross=', /crossorigin/.test(h))
console.log('title=', (h.match(/<title>.*<\/title>/) || [])[0])
const js = fs.readdirSync(path.join(root, 'assets')).filter(f => f.endsWith('.js'))
console.log('js files=', js)
